apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: #{Project.Cluster.Namespace}
resources:
- ../../base

patches:
  - target:
      kind: Deployment
      name: octopub-audit-deployment
    path: octopub-audits-deployment-mysql.yaml
  - target:
      kind: Service
      name: octopub-audit-cluster-ip
    path: octopub-audits-service-mysql.yaml
  - target: 
      kind: Ingress
      name: octopub-ingress
    path: octopub-ingress.yaml


secretGenerator:
  - name: database-credentials
    behavior: merge
    envs:
    - secrets.properties

configMapGenerator:
  - name: service-env-vars
    behavior: merge
    env: variables.properties

images:
  - name: octopussamples/octopub-audit-microservice-mysql
    newName: #{Octopus.Action.Package[octopub-audit-microservice-mysql].PackageId}
    newTag: #{Octopus.Action.Package[octopub-audit-microservice-mysql].PackageVersion}
