apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: #{Project.Cluster.Namespace}
resources:
- ../../base

secretGenerator:
  - name: database-credentials
    behavior: merge
    envs:
    - secrets.properties