apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- octopub-ingress.yaml
- octopub-products-mysql.yaml

secretGenerator:
  - name: database-credentials
    envs:
    - secrets.properties

configMapGenerator:
  - name: service-env-vars
    env: variables.properties

generatorOptions:
  disableNameSuffixHash: true