# Default values for octopub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

database:
  hostname: #{MySQL.Server.Name}
  port: #{MySQL.Server.Port}
  username: #{MySQL.Database.Admin.Username}
  password: #{MySQL.Database.Admin.Password}
  name: #{Project.Database.Name}
  migrateOnStartup: false

ingress:
  enabled: true
  className: #{Project.Ingress.ClassName}
  annotations: {
     }
  hosts:
    - host: #{Project.Host.Name}
      paths:
        - path: /api/products
          pathType: Prefix
          
service:
  type: ClusterIP
  port: 8083
          
image:
  repository: #{Octopus.Action.Package[octopub-products-microservice-mysql].PackageId}
  tag: #{Octopus.Action.Package[octopub-products-microservice-mysql].PackageVersion}          

replicaCount: 1

image:
  repository: octopussamples/octopub-products-microservice-mysql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

network:
  port: 8083

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 80
  annotations:
    # https://stackoverflow.com/a/76247614/8246539
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
