name: Build Products Kubecon
permissions:
  contents: write
  packages: write
'on':
   workflow_dispatch: {}
  # push:
  #   branches:
  #     - kube-con
  #   paths:
  #     - '**/*'
  #     - '!.github/badges/*'
  #     - '!README.md'
  #     - '!python/**/*'
   schedule:
   - cron: "*/10 * * * *" 

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Audit Microservice
        uses: ./github/java-microservice-kubecon
        with:
          run_number: ${{ github.run_number }}
          github_repo: ${{ github.repository }}
          github_token: ${{ github.token }}
          github_actor: ${{ github.actor }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          octopus_url: ${{ secrets.OCTOPUS_SAMPLES_URL }}
          octopus_apikey: ${{ secrets.OCTOPUS_SAMPLES_API_KEY }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          service_directory: products-microservice
          octopus_project_name: "Octopub-Helm-Product Service"

      # - name: Build Audits Helm Chart
      #   uses: ./github/helm
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     chart_directory: octopub-audits-mysql
      #     octopus_url: ${{ secrets.DSC_OCTOPUS_URL }}
      #     octopus_apikey: ${{ secrets.DSC_OCTOPUS_API }}