name: Zip MySQL scripts
permissions:
  contents: write
  packages: write
'on':
  workflow_dispatch: {}
  push:
    paths:
      - '**/*'
      - '!.github/badges/*'
      - '!README.md'
      - '!python/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Version
        run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Zip files
        uses: vimtor/action-zip@v1.2
        with:
            files: mysql
            dest: octopub.mysql.flyway.${{ env.PACKAGE_VERSION }}.zip